### ISSUE TITLE
Signaler une musique > Pas d'effet au clic

### ISSUE THREAD

**Issue by vqrvqrq** [hpruvot/dys-proj#105]
Prévoir un mail automatique d'envoi à contact@dyskit avec titre + nom de uploader de la musique

**Comment by AntoineWattier** [comment]
Done

**Comment by vqrvqrq** [comment]
*souhaiterais
(Ps : c'est pas mieux de mettre sur l'adresse contact@dyskit.com ?)
![capture d ecran 2015-05-12 a 22 13 44](https://cloud.githubusercontent.com/assets/4222039/7597508/4a8a596c-f8f4-11e4-880c-37b54057266f.png)

**Comment by AntoineWattier** [comment]
Nan c'est l'adresse qu'ils utilisent partout

**Comment by vqrvqrq** [comment]
Si du coup tu pouvais juste corriger la faute en ajoutant un *s à "souhaiterai", ce serait top ! :+1:

**Comment by AntoineWattier** [comment]
C'est fait ;)
