### ISSUE TITLE
Firefox > Pas possible d'ajouter une chanson à sa playlist au clic sur l'icon

### ISSUE THREAD

**Issue by vqrvqrq** [hpruvot/dys-proj#114]
![capture d ecran 2015-05-08 a 14 17 11](https://cloud.githubusercontent.com/assets/4222039/7536127/00f47a68-f58d-11e4-8228-a08c6509a255.png)

**Comment by vqrvqrq** [comment]
Je sais pas trop si cette issue et pour toi Antoine ou pour toi Hélène :(

**Comment by AntoineWattier** [comment]
C'était pour LN, mais j'ai fix :tongue:

**Comment by vqrvqrq** [comment]
Ahahah top :+1:
