### ISSUE TITLE
Au clic sur PP user > renvoyer sur son profil

### ISSUE THREAD

**Issue by vqrvqrq** [hpruvot/dys-proj#130]

**Comment by hpruvot** [comment]
PP user c'est quoi ?

**Comment by vqrvqrq** [comment]
Profil Pic du user, genre ça : 
![capture d ecran 2015-05-11 a 17 47 25](https://cloud.githubusercontent.com/assets/4222039/7568921/d45a2aa4-f805-11e4-8e90-51b1403eaf65.png)
