### ISSUE TITLE
Mobile > Edit settings

### ISSUE THREAD

**Issue by vqrvqrq** [hpruvot/dys-proj#133]
![img_8152](https://cloud.githubusercontent.com/assets/4222039/7555993/43d35f7e-f75f-11e4-9270-a7f2602f0643.PNG)

**Comment by vqrvqrq** [comment]
Les borders sont un peu dégueu mais c'est vraiment low priority. Au pire c'est pas grave.

**Comment by hpruvot** [comment]
Mmm c'est bizarre, si c'est iOS j'y peux rien :/
