### ISSUE TITLE
Admin > pas possible de bannir un user

### ISSUE THREAD

**Issue by vqrvqrq** [hpruvot/dys-proj#156]

**Comment by AntoineWattier** [comment]
Done, cela supprime le compte de l'utilisateur

**Comment by vqrvqrq** [comment]
Yes, top.

**Comment by AntoineWattier** [comment]
En local c'est ok et ça sera aussi en prod, mais pas sur Heroku

**Comment by vqrvqrq** [comment]
Ok, je testerai en prod.
