### ISSUE TITLE
Modifier son profil > Cancel my account

### ISSUE THREAD

**Issue by vqrvqrq** [hpruvot/dys-proj#158]
Pas possible de supprimer son compte

**Comment by AntoineWattier** [comment]
Essaye en créant un nouveau compte ça devrait marcher.

**Comment by vqrvqrq** [comment]
Non, toujours pas... :(

**Comment by vqrvqrq** [comment]
Non, toujours pas :(

**Comment by AntoineWattier** [comment]
Voir #156
