### ISSUE TITLE
Au clic sur profil à caractères spéciaux, page 500

### ISSUE THREAD

**Issue by vqrvqrq** [hpruvot/dys-proj#159]
"Effectivement lorsqu’on clique sur les profils des artistes L.A et BRÖ nous arrivons sur une page 500. 

Et si on clique sur le bouton « retour » de la page 500, la partie centrale diminue (voir capture d’écran). 

Est-il possible de regarder ce qui se passe ?"

![retour page 500](https://cloud.githubusercontent.com/assets/4222039/8202200/0cc47edc-14d8-11e5-9c87-1133c2b82552.png)

**Comment by AntoineWattier** [comment]
Done! je dois juste retirer les points des users qui en ont mis..

**Comment by vqrvqrq** [comment]
Ok, c'en est où du coup ?
