### ISSUE TITLE
Landing > "ondes sonores" sur grand écran exemple 17" elles ne continuent pas sur la droite 

### ISSUE THREAD

**Issue by vqrvqrq** [hpruvot/dys-proj#33]

**Comment by hpruvot** [comment]
Si ça marche quand tu refresh, mais forcément s'il resize à la mano les barres ne s'ajoutent et ne s'enlèvent pas. Ça bouffe de la ressource de tout modifier et adapter au resize donc je dis non pour cette issue :)
