### ISSUE TITLE
Landing > *Firefox* - border sur le champs newsletter

### ISSUE THREAD

**Issue by vqrvqrq** [hpruvot/dys-proj#38]
![capture d ecran 2015-03-12 a 14 35 51](https://cloud.githubusercontent.com/assets/4222039/6618743/7304a3f2-c8c5-11e4-8a62-9235ee4aaa99.png)

**Comment by hpruvot** [comment]
C'est normal c'est le champ required html qui fait ça, je peux rien faire... Tout comme chrome qui met un background jaune dégueu quand on rentre une adresse déjà connue de chrome
