### ISSUE TITLE
Upload > Message d'erreur

### ISSUE THREAD

**Issue by vqrvqrq** [hpruvot/dys-proj#66]
![capture d ecran 2015-04-29 a 19 03 15](https://cloud.githubusercontent.com/assets/4222039/7396567/7bd9757c-eea2-11e4-8d48-3540409a0a8d.png)

**Comment by AntoineWattier** [comment]
Ça dépend de la connexion et de si tu attends la fin de l'upload ou pas, je peux rien y faire à part traduire le message
