### ISSUE TITLE
Track dans playlist > Ajouter au bouton rond (see more) les actions ci-dessous

### ISSUE THREAD

**Issue by vqrvqrq** [hpruvot/dys-proj#69]
- supprimer 
- partage RS
  ![capture d ecran 2015-04-30 a 19 44 15](https://cloud.githubusercontent.com/assets/4222039/7418886/9ac67140-ef71-11e4-89d7-586f8afb455f.png)

**Comment by hpruvot** [comment]
On a mis supprimer des coups de coeur uniquement
