### ISSUE TITLE
Edit compte > bio trop longue

### ISSUE THREAD

**Issue by vqrvqrq** [hpruvot/dys-proj#91]
![capture d ecran 2015-05-07 a 11 40 27](https://cloud.githubusercontent.com/assets/4222039/7512529/eaa48d82-f4ad-11e4-9426-5f25acb064b8.png)

**Comment by AntoineWattier** [comment]
Ok fixed

**Comment by vqrvqrq** [comment]
140 caractères, pas 150 du coup.
![capture d ecran 2015-05-07 a 14 04 38](https://cloud.githubusercontent.com/assets/4222039/7514901/4199e768-f4c2-11e4-9903-0f4a4764a645.png)
